### ISSUE TITLE
Repository not HACS 1.0.2 compliant

### ISSUE THREAD

**Issue by remyderuysscher** [ping-localhost/seventeen-track-card#3]
The repository cannot be found in HACS and it's not possible to manual add this repository

**Comment by ping-localhost** [comment]
It is indeed not in the standard HACS store, however, I'm able to add the repository just fine. Can you please try again:

![image](https://user-images.githubusercontent.com/37925797/86447417-9d586400-bd15-11ea-809f-9cf816e5015f.png)

**Comment by remyderuysscher** [comment]
Thanks, category was set wrong. My mistake!
