### ISSUE TITLE
Display location of last tracking update

### ISSUE THREAD

**Issue by speedst3r** [ping-localhost/seventeen-track-card#6]
**Is your feature request related to a problem? Please describe.**
Could the card also have the ability to display the location? I receive packages from other states and countries, so it would be useful to see where the last tracking update was lodged.

**Describe the solution you'd like**
Static inclusion of ${enum.location} or via card option (e.g. display_location: true)

**Comment by ping-localhost** [comment]
Sounds like a good addition. Will work on it tonight.

**Comment by ping-localhost** [comment]
Took a little longer because I got distracted, but I've added it (in its simplest form). 😄
